CREATE TABLE players (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    nickname VARCHAR(50) NOT NULL,
    email VARCHAR(100),
    level INT DEFAULT 1,
    experience BIGINT DEFAULT 0,
    hp INT DEFAULT 1000,
    hp_max INT DEFAULT 1000,
    mp INT DEFAULT 500,
    mp_max INT DEFAULT 500,
    strength INT DEFAULT 10,
    constitution INT DEFAULT 10,
    agility INT DEFAULT 10,
    intelligence INT DEFAULT 10,
    luck INT DEFAULT 10,
    map_id VARCHAR(50) DEFAULT 'xiangyang',
    position_x INT DEFAULT 1000,
    position_y INT DEFAULT 1000,
    silver BIGINT DEFAULT 1000,
    gold BIGINT DEFAULT 0,
    reputation BIGINT DEFAULT 0,
    faction_id BIGINT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_username (username),
    INDEX idx_map_id (map_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;